// <autogenerated>
//   This file was generated by T4 code generator Exec.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using PLKJDS.Entity;
using System.Collections.Generic;
using PLKJDS.Data.IRepositories;

namespace PLKJDS.Data.Repositories
{
	/// <summary>
    /// IEducationRepository仓储接口
    /// </summary>
    public partial class EducationRepository : RepositoryBase<Education>, IEducationRepository
    {
	 
    }
}
