// <autogenerated>
//   This file was generated by T4 code generator Exec.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



using System;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Configuration;

using PLKJDS.Entity;

namespace PLKJDS.Mapping.Configurations
{
	/// <summary>
    /// 数据表映射
    /// </summary>
    partial class UserCourseConfiguration : EntityConfiguration<UserCourse>
    {
        /// <summary>
        /// 数据表映射构造函数
        /// </summary>
        public UserCourseConfiguration()
        {
            UserCourseConfigurationDefault();
            UserCourseConfigurationAppend();
        }

        /// <summary>
        /// 默认的数据映射
        /// </summary>
        public void UserCourseConfigurationDefault()
        {
          
			this.ToTable("UserCourse");
            this.HasKey(t => t.ID);
            //this.Property(p => p.LastModifyUserCourse).HasMaxLength(100);
			//this.Property(p => p.CreateUserCourse).IsRequired().HasMaxLength(100);

        }

        /// <summary>
        /// 数据映射
        /// </summary>
        partial void UserCourseConfigurationAppend();
    }
}
