// <autogenerated>
//   This file was generated by T4 code generator Exec.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using PLKJDS.Entity;

namespace PLKJDS.Data.IRepositories
{
	/// <summary>
    /// IResumeConfigRepository仓储接口
    /// </summary>
    public partial interface IResumeConfigRepository : IRepositoryBase<ResumeConfig>
    {
	 
    }
}
