// <autogenerated>
//   This file was generated by T4 code generator Exec.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using PLKJDS.Entity;

namespace PLKJDS.Data.IRepositories
{
	/// <summary>
    /// ITrainExperienceRepository仓储接口
    /// </summary>
    public partial interface ITrainExperienceRepository : IRepositoryBase<TrainExperience>
    {
	 
    }
}
